# Generated by Django 4.2.2 on 2023-07-11 08:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="default-user-avatar.jpg", null=True, upload_to=accounts.models.get_image_filename
            ),
        ),
    ]
