# Generated by Django 4.2.7 on 2023-11-29 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_emailforchanging"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailForChanging",
            new_name="ChangedEmail",
        ),
    ]
