# Generated by Django 4.2.3 on 2023-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="description",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
