# Generated by Django 4.2.5 on 2023-09-09 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="creator",
            new_name="user",
        ),
    ]
