# Generated by Django 4.2.5 on 2023-10-06 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_savedchat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="description",
            field=models.TextField(
                default=datetime.datetime(2023, 10, 6, 8, 28, 23, 78151, tzinfo=datetime.timezone.utc), max_length=400
            ),
            preserve_default=False,
        ),
    ]
