# Generated by Django 4.2.5 on 2023-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_chat_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
