# Generated by Django 4.2.5 on 2023-10-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_chat_description_alter_chat_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
