# Generated by Django 4.2.5 on 2023-10-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_chatlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(max_length=792, null=True),
        ),
    ]
