# Generated by Django 4.2.7 on 2023-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="room",
            field=models.CharField(
                choices=[("books", "books"), ("cinema", "cinema"), ("music", "music"), ("games", "games")],
                max_length=50,
            ),
        ),
    ]
