# Generated by Django 4.2.6 on 2023-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_message_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="room",
            field=models.CharField(
                choices=[("books", "books"), ("cinema", "cinema"), ("music", "music"), ("games", "games")],
                max_length=50,
            ),
        ),
    ]
