# Generated by Django 4.2.6 on 2023-12-10 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_alter_chat_room"),
        ("chat", "0017_alter_chat_room"),
    ]

    operations = []
