# Generated by Django 5.0.1 on 2024-01-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0018_merge_0016_alter_chat_room_0017_alter_chat_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, max_length=792, null=True),
        ),
    ]
