---
- name: Server setup
  hosts: all
  become: true

  vars:
    docker_edition: 'ce'
    docker_install_compose_plugin: true

  tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: Installing required packages
      apt: name={{item}} state=present
      with_items:
        - git
        - python3-pip

    - name: Docker python package
      ansible.builtin.pip:
        name: docker


  roles:
    - geerlingguy.docker
