---
- name: Server setup
  hosts: all
  become: true

  vars:
    docker_edition: 'ce'
    docker_install_compose_plugin: true

  tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: List packages
      shell: dpkg-query -f '${binary:Package}\n' -W
      register: packages

    - name: Print packages
      debug:
        msg: "{{ packages.stdout_lines }}"

    - name: Stop and disable unneeded services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - nginx

    - name: Installing required packages
      apt: name={{item}} state=present
      with_items:
        - git
        - python3-pip

    - name: Removing unneeded packages
      apt: name={{item}} state=absent
      with_items:
        - nginx

    - name: Docker python package
      ansible.builtin.pip:
        name: docker


  roles:
    - geerlingguy.docker
