# Generated by Django 5.0 on 2023-12-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=255)),
                ("country_code", models.CharField(max_length=2)),
                ("is_spam", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EmailInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("country_code", models.CharField(max_length=2)),
                ("is_disposable", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=False)),
                ("is_spam", models.BooleanField(default=False)),
            ],
        ),
    ]
