---
- name: Build an image
  delegate_to: localhost
  community.docker.docker_image:
    source: build
    build:
      path: ../../../
      dockerfile: .github/scripts/deploy/Dockerfile
      nocache: true
      pull: true
      rm: true

    force_source: true
    force_tag: true
    name: chat-{{ img_name }}
    tag: latest
    archive_path: /tmp/chat_image.tar
  register: build_result
  changed_when: build_result is changed

- name: Save build logs to a file
  copy:
    content: "{{ build_result.stdout }}"
    dest: /tmp/image_build.log
