# Generated by Django 5.0.1 on 2024-01-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="original_file_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
