---
name: Deploy
'on':
  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Repository branch to deploy'     
        required: true
        default: 'master'
      server:
        description: 'Server to deploy'
        required: true
        default: 'default'

  workflow_call:
    secrets:
      VAULT_PASS:
        description: 'Vault password'
        required: true

permissions: write-all

jobs:
  black:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      SERVER: ${{ github.event_name == 'workflow_dispatch' &&  github.event.inputs.server || 'default' }}
      BRANCH_NAME: ${{ github.event_name == 'workflow_dispatch' &&  github.event.inputs.deploy_branch || github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install ansible-core requests docker
          cd .github/scripts/deploy
          ansible-galaxy collection install -r requirements.yml

      - name: run playbook
        run: |
          eval `ssh-agent -s`
          cd .github/scripts/deploy
          echo "${{ secrets.VAULT_PASS }}" > $RUNNER_TEMP/.vault_pass

          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-vault view --vault-password-file=$RUNNER_TEMP/.vault_pass files/vault1 | ssh-add -
          ansible-playbook deploy.yml                        \
            -i ./inventory                                   \
            --vault-password-file $RUNNER_TEMP/.vault_pass   \
            -e CI=true                                       \
            -e BRANCH=$BRANCH_NAME                           \
            -e SERVER=$SERVER

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: /tmp/*.log

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const msg = branch === 'master' ?
              '🚀 Deployed here: https://back.4rooms.pro/' :
              '🚀 Deployed here: https://testback.4rooms.pro/';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
