---
name: Reviewdog - python
'on': [pull_request]
permissions: write-all

jobs:
  black:
    name: black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install specific version black (this step is not required. default is "black[jupyter]")
      # - run: pip install black
      - uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with a warning.
          level: warning
